version: "3.7"
services:
  cloudyadmindb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Passw0rd_
    volumes:
      - cloudyadminvolume:/var/opt/mssql
    container_name: cloudy-db
    networks:
        - cloudyadminnetwork
  cloudyadminapp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - CLOUDYBACK_OUTER_PERSIST_FOLDER=${PWD}/CloudyBack/config_storage
      - ConnectionStrings__DefaultConnection=Server=cloudyadmindb;Database=CloudyDb;User Id=sa;Password=Passw0rd_;Encrypt=False;TrustServerCertificate=True;
    volumes:
      - ./CloudyBack/config_storage:/app/bin/Debug/net8.0/persist
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    depends_on:
      - cloudyadmindb
    container_name: cloudyadminapp
    networks:
        - cloudyadminnetwork
volumes:
  cloudyadminvolume:
networks:
  cloudyadminnetwork:
    driver: bridge
