// <auto-generated />
using System;
using Kjkardum.CloudyBack.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kjkardum.CloudyBack.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250516203052_AuditLogsOnResource")]
    partial class AuditLogsOnResource
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kjkardum.CloudyBack.Domain.Entities.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionDisplayText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActionMetadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.HasIndex("Timestamp");

                    b.ToTable("AuditLogEntries");
                });

            modelBuilder.Entity("Kjkardum.CloudyBack.Domain.Entities.BaseResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UpdatedAt");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Kjkardum.CloudyBack.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Kjkardum.CloudyBack.Domain.Entities.ResourceGroup", b =>
                {
                    b.HasBaseType("Kjkardum.CloudyBack.Domain.Entities.BaseResource");

                    b.ToTable("ResourceGroups");
                });

            modelBuilder.Entity("Kjkardum.CloudyBack.Domain.Entities.ResourceGroupedBaseResource", b =>
                {
                    b.HasBaseType("Kjkardum.CloudyBack.Domain.Entities.BaseResource");

                    b.Property<Guid>("ResourceGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("ResourceGroupId");

                    b.ToTable((string)null);
                });

            modelBuilder.Entity("Kjkardum.CloudyBack.Domain.Entities.PostgresDatabaseResource", b =>
                {
                    b.HasBaseType("Kjkardum.CloudyBack.Domain.Entities.ResourceGroupedBaseResource");

                    b.Property<string>("AdminPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdminUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PostgresDatabaseServerResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("PostgresDatabaseServerResourceId");

                    b.ToTable("PostgresDatabaseResources");
                });

            modelBuilder.Entity("Kjkardum.CloudyBack.Domain.Entities.PostgresServerResource", b =>
                {
                    b.HasBaseType("Kjkardum.CloudyBack.Domain.Entities.ResourceGroupedBaseResource");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<string>("SaPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SaUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("PostgresServerResources");
                });

            modelBuilder.Entity("Kjkardum.CloudyBack.Domain.Entities.AuditLogEntry", b =>
                {
                    b.HasOne("Kjkardum.CloudyBack.Domain.Entities.BaseResource", "Resource")
                        .WithMany("AuditLogEntries")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Kjkardum.CloudyBack.Domain.Entities.ResourceGroupedBaseResource", b =>
                {
                    b.HasOne("Kjkardum.CloudyBack.Domain.Entities.ResourceGroup", "ResourceGroup")
                        .WithMany("Resources")
                        .HasForeignKey("ResourceGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ResourceGroup");
                });

            modelBuilder.Entity("Kjkardum.CloudyBack.Domain.Entities.PostgresDatabaseResource", b =>
                {
                    b.HasOne("Kjkardum.CloudyBack.Domain.Entities.PostgresServerResource", "PostgresDatabaseServerResource")
                        .WithMany("PostgresDatabaseResources")
                        .HasForeignKey("PostgresDatabaseServerResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PostgresDatabaseServerResource");
                });

            modelBuilder.Entity("Kjkardum.CloudyBack.Domain.Entities.BaseResource", b =>
                {
                    b.Navigation("AuditLogEntries");
                });

            modelBuilder.Entity("Kjkardum.CloudyBack.Domain.Entities.ResourceGroup", b =>
                {
                    b.Navigation("Resources");
                });

            modelBuilder.Entity("Kjkardum.CloudyBack.Domain.Entities.PostgresServerResource", b =>
                {
                    b.Navigation("PostgresDatabaseResources");
                });
#pragma warning restore 612, 618
        }
    }
}
