apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://cloudyprometheuscontainer:9090
    basicAuth: true
    basicAuthUser: admin
    secureJsonData:
      basicAuthPassword: $PROMETHEUS_DATASOURCE_PASSWORD
