version: "3.7"
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Passw0rd_
    volumes:
      - db-data:/var/opt/mssql
    ports:
      - "1433:1433"
    container_name: cloudy-db
volumes:
  db-data:
